[workspace]
members = [
    "policy-controller",
    "policy-controller/core",
    "policy-controller/grpc",
    "policy-controller/k8s/api",
    "policy-controller/k8s/index",
    "policy-controller/k8s/status",
    "policy-test",
]

[profile.release]
lto = "thin"

[patch.crates-io]
kubert = { git = "https://github.com/amit-62/kubert.git", branch = "my-v15" }
